### ISSUE TITLE
Multisite issue with theme activation

### ISSUE THREAD

**Issue by mallorydxw** [dxw/wpc#17]
`bin/setup` complains:

```
usage: wp theme enable <theme> [--network] [--activate]
```

This is the contents of `setup/internal.php`:

```
wp theme enable --network 
```

(the line ends with a space)

I think this may be the cause:

```
    perl -pi -e 's/!!!THEMEENABLE!!!/wp theme enable --network $theme/g' setup/internal.sh
```

(Perl interpreting `$theme` as a variable)

**Comment by RobjS** [comment]
I can't replicate this. I did `wpc_init gds_blogs --multisite`, and the `setup/internal.sh` has:

```
wp theme enable --network $theme
```

So I'm guessing this may be another shell version issue.

**Comment by mallorydxw** [comment]
I just ran wpc_init again and I'm no longer seeing this issue.
