### ISSUE TITLE
Add a --reset option to bin/setup?

### ISSUE THREAD

**Issue by mallorydxw** [dxw/wpc#23]
Not everything in `bin/setup` (such as the title) gets updated when it gets run a second time.

When `bin/setup` is run on an installation where it's already been run, it should produce a warning.

When `bin/setup --reset` is run, it should delete the database before running so that everything gets reset.

**Comment by RobjS** [comment]
I think https://github.com/dxw/wpc/pull/39 makes this more of a priority. The rule-them-all  convention states: 
"`script/setup` is used to set up a project in an initial state. This is typically run after an initial clone, or, to reset the project back to its initial state."

Our setup script won't currently do the second of those. But we can handle that after doing the initial rule-them-all implementation.

**Comment by mallorydxw** [comment]
I think to make this more discoverable we could make it so that if you run `script/setup` it checks if the volume exists, and if it does it asks you if you'd like to reset everything or stop.

Resetting is pretty simple: `docker-compose down --volumes`
