### ISSUE TITLE
Do we need external.sh anymore?

### ISSUE THREAD

**Issue by RobjS** [dxw/wpc#42]
The only thing this does is install whippet deps, which is now handled by `script/bootstrap`. 

In theory, I guess it could still be used for running commands outside the container, but is that realistically something we'll need? If not, we should just remove `external.sh` altogether.

**Comment by mallorydxw** [comment]
Yeah we don't need it. I didn't notice that when migrating `bin/setup` to `script/setup` we just removed all references to the file.
