### ISSUE TITLE
Ask before overwriting files

### ISSUE THREAD

**Issue by mallorydxw** [dxw/wpc#8]
Might be a useful thing to add. But not a priority because we're intending to track these files with git.

**Comment by RobjS** [comment]
@tomdxw Which do you think is preferable - checking for one/some/all of the files we expect to be preset before doing anything, giving the choice at that point, then overwriting all the files if the user decides to continue? Or asking on a file-by-file basis if the user wants to overwrite?

i.e.

`It looks like this is already a wpc project. Continue and overwrite the current wpc files? (y/n)` (then overwrite all files)

or

`File [x] already exists. Overwrite it? (y/n)` (then just overwrite that specific file)

I feel like the latter is probably preferable, but it makes the process (if the files do exist) a bit clunkier and less user-friendly.

**Comment by mallorydxw** [comment]
I agree that the second option is preferable. It's easier to implement, and allows users to overwrite some files but not others.

Hopefully people won't be running `wpc_init` a lot (ideally it would be done once and committed) so if it's slightly annoying for the user then that's not too much of a problem.
